Coursework.Web/Controllers/FlowerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Formatting;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Coursework.Entity.Services;
using Coursework.Web.Models;
using Microsoft.AspNet.Identity;

namespace Coursework.Web.Controllers
{
    public class FlowerController : Controller
    {
        private readonly IUserService _userService;
        private readonly IFlowerService _flowerService;
        private readonly ICommentService _commentService;
        private readonly IPictureService _pictureService;

        public FlowerController(IUserService userService, IFlowerService flowerService, ICommentService commentService, IPictureService pictureService)
        {
            _userService = userService;
            _flowerService = flowerService;
            _commentService = commentService;
            _pictureService = pictureService;
        }
        // GET: Flower
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetFlowers()
        {
            var result = _flowerService.GetAllFlowers();
            var flowers = result.Select(Mapper.Map<FlowerViewModel>).ToList();
            return View(flowers);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(FlowerViewModel model)
        {
            if (ModelState.IsValid)
            {
                _flowerService.CreateFlower(User.Identity.GetUserId(), model.FlowerName);
                return RedirectToAction("GetCurrentUser", "User");
            }
            return View(model);
        }

        public ActionResult Search(string s)
        {
            var result = _flowerService.GetAllFlowers();
            var flowers = result.Select(Mapper.Map<FlowerViewModel>).ToList();
            List<FlowerViewModel> res = new List<FlowerViewModel>();
            string tmp;

            foreach (var c in flowers)
            {
                tmp = c.FlowerName.ToLower();

                if (tmp.Contains(s.ToLower()))
                    res.Add(c);

            }
            return View(res);
        }

        public ActionResult GetFlower(long id)
        {
            var result = _flowerService.GetFlower(id);
            var _flower = Mapper.Map<FlowerViewModel>(result);

            if (result == null)
                return new HttpNotFoundResult();
            return View(_flower);
        }

        [HttpGet]
        public ActionResult Comment(long id)
        {
            CommentViewModel comment = new CommentViewModel();
            comment.FlowerId = id;
            return View(comment);
        }

        [HttpPost]
        public ActionResult Comment(CommentViewModel model)
        {
            if (ModelState.IsValid)
            {
                _commentService.CreateComment(User.Identity.GetUserId(), model.FlowerId, model.Text);
                return RedirectToAction("GetFlower", new { id = model.FlowerId });
            }
            return View(model);
        }


        [HttpGet]
        public ActionResult AddPhoto(long id)
        {
            PictureViewModel picture = new PictureViewModel();
            picture.FlowerId = id;
            return View(picture);
        }

        public ActionResult AddPhoto(HttpPostedFileBase uploadImage, PictureViewModel model)
        {
            if (ModelState.IsValid && uploadImage!=null)
            {
                byte[] imageData = null;

                using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                {
                    imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                }
                _pictureService.CreatePicture(model.FlowerId, imageData);
                return RedirectToAction("GetFlower", new { id = model.FlowerId });
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(long id)
        {
            var result = _flowerService.GetFlower(id);
            var _flower = Mapper.Map<FlowerViewModel>(result);
            return View(_flower);
        }

        [HttpPost]
        public ActionResult Delete(long id, FormCollection form)
        {
            if (ModelState.IsValid)
            {
                _flowerService.DeleteFlower(id);
                return RedirectToAction("GetCurrentUser", "User");
            }
            return View();
        }
    }
}

Coursework.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Coursework.Entity.Services;
using Coursework.Web.Models;
using Microsoft.AspNet.Identity;

namespace Coursework.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetCurrentUser()
        {
            var result = _userService.GetUser(User.Identity.GetUserId());
            var user = Mapper.Map<UserViewModel>(result);
            if (result == null)
                return new HttpNotFoundResult();
            return View(user);
        }

        public ActionResult GetUser(string id)
        {
            var result = _userService.GetUser(id);
            var user = Mapper.Map<UserViewModel>(result);
            if (result == null)
                return new HttpNotFoundResult();
            return View(user);
        }

        [HttpGet]
        public ActionResult Buy()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Buy(int count)
        {
            if (ModelState.IsValid)
            {
                _userService.Buy(count, User.Identity.GetUserId());               
            }
            return RedirectToAction("GetCurrentUser");
        }
    }
}

Coursework.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Flowerade</title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            @if (User.Identity.IsAuthenticated)
            {
                @Html.ActionLink("Flowerade", "GetCurrentUser", "User", new {area = ""}, new {@class = "navbar-brand"})
            }
            else
            {
                @Html.ActionLink("Flowerade", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            }

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("My profile", "GetCurrentUser", "User")</li>
                        <li>@Html.ActionLink("Purchase more flowers", "Buy", "User")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    }
                </ul>
                @if (User.Identity.IsAuthenticated)
                {
                    <form class="navbar-form navbar-left" role="search" action='@Url.Action("Search", "Flower")'>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search for flowers" name="s" />
                            <input type="submit" class="hidden" />
                        </div>
                    </form>
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Flowerade</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>